fast: |
  For the situation {situation} and the {vrd} that is {text} predict only one Label among Support or Oppose based on whether the {vrd} supports or opposes the Situation or Either if it depends on context.
  Do not provide any explanation or reasoning. Strictly mention the Label only without any reasoning in the last line as "Fast thinking Label: <Supports or Opposes or Either>"

slow: |
  Please structure your response into two main sections: Thought and Solution.
  A situation presents a hypothetical situation designed to explore potential actions and their consequences.
  Generally, in a situation, the Actor (main individual or group) interacts with Side Actors (other individuals or groups).
  For the given situation {situation}, assume you are the Actor who believes in {vrd} that is {text}.
  Analyze the situation through the lens of the {vrd}, discussing your interpretations, conflicts, and dilemmas.
  Explore how different perspectives within this {vrd}, {text} might lead to varied judgments.
  Strictly provide your reasoning in the Thoughts Section and based on your reasoning determine whether the {vrd} Supports or Opposes the situation or Either if it depends on the context.
  Provide the output in the Solution Section as 'Slow thinking label: <Supports or Opposes or Either>'

anchor: |
  The {vrd} that is {text} seems to {anchor} the situation {situation}